topeduc_bis/config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
      resources :users
      resources :calendars
      resources :carte_vitales
      resources :clients
      resources :contracts
      resources :diplomas
      resources :factures
      resources :ids
      resources :kbis
      resources :messages
      resources :permis_bs
      resources :requests
      resources :resumes
      resources :ribs

      root to: "users#index"
    end
# Factures
	resources :facture
# Clients
	resources :client
# Messages
	resources :message
	
# Contracts
	resources :request
	resources :contract

# Upload Documents: 
	resources :resume
	resources :permis_b
	resources :diploma
	resources :kbi
	resources :id
	resources :carte_vitale
	resources :rib

# Calendar:
	resources :calendar

# DEVISE: 
	devise_for :users, controllers: {
        sessions: 'users/sessions', registrations: 'users/registrations'
      }
 
# Other Routes:
	get 'static/home'
	get 'static/secret_page'
	get 'static/test'
	root 'static#home'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

topeduc_bis/app/views/layouts/_footer.html.erb
<footer id="footer" class="footer">
    <div class="container text-center">

      <h3>Nos réseaux !</h3>

     
      <!-- End newsletter-form -->
      <ul class="social-links">
        <li><a href="#link"><i class="fa fa-twitter fa-fw"></i></a></li>
        <li><a href="#link"><i class="fa fa-facebook fa-fw"></i></a></li>
        <li><a href="#link"><i class="fa fa-google-plus fa-fw"></i></a></li>
        <li><a href="#link"><i class="fa fa-dribbble fa-fw"></i></a></li>
        <li><a href="#link"><i class="fa fa-linkedin fa-fw"></i></a></li>
      </ul>
      
      ©2016 Mentor Theme. All rights reserved
      <div class="credits">
        <!--
          All the links in the footer should remain intact.
          You can delete the links only if you purchased the pro version.
          Licensing information: https://bootstrapmade.com/license/
          Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Mentor
        -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade.com</a>
      </div>
    </div>
  </footer>

topeduc_bis/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag('logo.jpg', width: 170, height: 50), root_path, :class => "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        
          <ul class="nav navbar-nav navbar-right">
            <% if current_page?(root_path) %>
              <li><a href="#feature">Identité</a></li>
              <li><a href="#organisations">Engagements</a></li>
              <li><a href="#work-shop">Valeurs</a></li>
              <li><a href="#faculity-member">Equipe</a></li>
              <li><a href="#contact">Contact</a></li>
            <% else %>
              <li> <%= link_to 'Home', root_path %></li>
              <li><%= link_to 'Dashboard', static_secret_page_path %></li>
              <li><%= link_to 'Messages', message_index_path %></li>
              <li><%= link_to 'Calendrier', calendar_index_path %></li>
            <% end %>

          <% if user_signed_in? %>
            <li><a href="#pricing"><%= button_to('Me déconnecter', destroy_user_session_path, method: :delete, :class => "btn-trial") %></a></li>
            <li><%= link_to 'Mon profil', static_secret_page_path %></li>
          <% else %>
            <li><%= link_to "S'inscrire", new_user_registration_path %></a></li>
            <li class="btn-trial"><%= link_to "Se connecter", user_session_path %></a></li>
          <% end %>
          </ul>
      </div>
    </div>
  </nav>

  <%= render "layouts/flash" %>

topeduc_bis/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GestionTopeduc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans|Candal|Alegreya+Sans">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  
  </head>

  <%= render 'layouts/navbar' %>
  
  <body>
    <%= yield %>
  </body>

  <%= render 'layouts/footer' %>

</html>